print ('arithmetic operators')
print (1 + 1)
print (2 - 1)
print (2 * 2)
print (2 ** 2)
print (20 / 5)
print (20 / 6)
print (20 % 6)
print ('arithmetic operators with strings')
print ('a' + 'ab')
print ('abc' * 3)
print ('Comparison, Logical, and Membership operators')
print (True == True)
print (4 < 5)
print (5 <= 5)
print (5 > 2)
print (5 >= 2)
print (True and True)
print (True and False)
print (True or False)
print (False or False)
print (not True)
print (not False)
print ('Membership operators in and not in')
print (10 not in  [1,2,3,4])
print (1 in  [1,2,3,4])
print ('cat' in 'my pet cat')